# Generated by Django 4.1.7 on 2023-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_tag_course_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('CIN', models.CharField(max_length=20)),
                ('categories', models.ManyToManyField(to='one.category')),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='course',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
